default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: '344312'
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: desconto-inss_development

test:
  <<: *default
  database: desconto-inss_test

production:
  <<: *default
  database: desconto-inss_production
